### ISSUE TITLE
Specificatie region-growing algoritme

### ISSUE THREAD

**Issue by lars-at-styx** [Geonovum/3dbasisvoorziening#2]
In het huidige document staat onder 3.4 de LoD1.3 reconstructie beschreven. Als punt 2 wordt genoemd dat vlakken in de puntenwolk met behulp van een 'region-growing' algoritme worden geidentificeerd. Zou iets meer helderheid (zoals een bronvermelding van een paper die dit algoritme beschrijft of een specifieke naam voor het algoritme) gegeven kunnen worden omtrent welk algoritme dit precies is?

**Comment by Ylannl** [comment]
Dit is een vrij standaard algoritme, zoals bijvoorbeeld beschreven (als surface growing) in 
```
@inbook{
title = "Visualisation and structuring of point clouds",
author = "G. Vosselman and R. Klein",
year = "2010",
language = "English",
isbn = "978-1904445-87-6",
pages = "45--81",
editor = "M.G. Vosselman and H.G. Maas",
booktitle = "Airborne and terrestrial laser scanning",
publisher = "CRC Press",
address = "United Kingdom",
}
```
